dependencies:
- name: elasticsearch
  version: 6.8.13
  repository: https://helm.elastic.co
  condition: elasticsearch.enabled
- name: mongodb
  version: 10.0.5
  repository: https://charts.bitnami.com/bitnami
  condition: mongodb.enabled
